// The 99 Names of Allah (Asma-ul-Husna)
// arabic — Arabic script, translit — transliteration,
// en — English meaning, sq — Albanian meaning
export const NAMES = [
  { n: 1,  arabic: "ٱلرَّحْمَٰن",  translit: "Ar-Rahman",    en: "The Most Merciful",            sq: "Mëshiruesi" },
  { n: 2,  arabic: "ٱلرَّحِيم",   translit: "Ar-Rahim",     en: "The Most Compassionate",       sq: "Mëshirëbërësi" },
  { n: 3,  arabic: "ٱلْمَلِك",    translit: "Al-Malik",     en: "The King",                     sq: "Sunduesi" },
  { n: 4,  arabic: "ٱلْقُدُّوس",   translit: "Al-Quddus",    en: "The Most Holy",                sq: "I Shenjti" },
  { n: 5,  arabic: "ٱلسَّلَام",    translit: "As-Salam",     en: "The Source of Peace",          sq: "Paqedhënësi" },
  { n: 6,  arabic: "ٱلْمُؤْمِن",   translit: "Al-Mu'min",    en: "The Giver of Security",        sq: "Siguruesi" },
  { n: 7,  arabic: "ٱلْمُهَيْمِن",  translit: "Al-Muhaymin",  en: "The Guardian",                 sq: "Mbikëqyrësi" },
  { n: 8,  arabic: "ٱلْعَزِيز",    translit: "Al-'Aziz",     en: "The Almighty",                 sq: "I Gjithëfuqishmi" },
  { n: 9,  arabic: "ٱلْجَبَّار",    translit: "Al-Jabbar",    en: "The Compeller",                sq: "Ngadhënjyesi" },
  { n: 10, arabic: "ٱلْمُتَكَبِّر",  translit: "Al-Mutakabbir", en: "The Supreme in Greatness",    sq: "Madhështori" },
  { n: 11, arabic: "ٱلْخَالِق",    translit: "Al-Khaliq",    en: "The Creator",                  sq: "Krijuesi" },
  { n: 12, arabic: "ٱلْبَارِئ",    translit: "Al-Bari'",     en: "The Originator",               sq: "Filluesi" },
  { n: 13, arabic: "ٱلْمُصَوِّر",   translit: "Al-Musawwir",  en: "The Fashioner",                sq: "Formësuesi" },
  { n: 14, arabic: "ٱلْغَفَّار",    translit: "Al-Ghaffar",   en: "The Constant Forgiver",        sq: "Falësi i Madh" },
  { n: 15, arabic: "ٱلْقَهَّار",    translit: "Al-Qahhar",    en: "The Subduer",                  sq: "Mposhtësi" },
  { n: 16, arabic: "ٱلْوَهَّاب",    translit: "Al-Wahhab",    en: "The Bestower",                 sq: "Dhuruesi" },
  { n: 17, arabic: "ٱلرَّزَّاق",    translit: "Ar-Razzaq",    en: "The Provider",                 sq: "Furnizuesi" },
  { n: 18, arabic: "ٱلْفَتَّاح",    translit: "Al-Fattah",    en: "The Opener",                   sq: "Zgjidhësi" },
  { n: 19, arabic: "ٱلْعَلِيم",    translit: "Al-'Alim",     en: "The All-Knowing",              sq: "I Gjithëdijshmi" },
  { n: 20, arabic: "ٱلْقَابِض",    translit: "Al-Qabid",     en: "The Withholder",               sq: "Shtrënguesi" },
  { n: 21, arabic: "ٱلْبَاسِط",    translit: "Al-Basit",     en: "The Extender",                 sq: "Zgjeruesi" },
  { n: 22, arabic: "ٱلْخَافِض",    translit: "Al-Khafid",    en: "The Abaser",                   sq: "Përulësi" },
  { n: 23, arabic: "ٱلرَّافِع",    translit: "Ar-Rafi'",     en: "The Exalter",                  sq: "Lartësuesi" },
  { n: 24, arabic: "ٱلْمُعِزّ",    translit: "Al-Mu'izz",    en: "The Honourer",                 sq: "Nderuesi" },
  { n: 25, arabic: "ٱلْمُذِلّ",    translit: "Al-Mudhill",   en: "The Humiliator",               sq: "Poshtëruesi" },
  { n: 26, arabic: "ٱلسَّمِيع",    translit: "As-Sami'",     en: "The All-Hearing",              sq: "Gjithëdëgjuesi" },
  { n: 27, arabic: "ٱلْبَصِير",    translit: "Al-Basir",     en: "The All-Seeing",               sq: "Gjithëshikuesi" },
  { n: 28, arabic: "ٱلْحَكَم",     translit: "Al-Hakam",     en: "The Judge",                    sq: "Gjykatësi" },
  { n: 29, arabic: "ٱلْعَدْل",     translit: "Al-'Adl",      en: "The Utterly Just",             sq: "I Drejti" },
  { n: 30, arabic: "ٱللَّطِيف",    translit: "Al-Latif",     en: "The Subtle, The Kind",         sq: "I Buti" },
  { n: 31, arabic: "ٱلْخَبِير",    translit: "Al-Khabir",    en: "The All-Aware",                sq: "I Gjithëinformuari" },
  { n: 32, arabic: "ٱلْحَلِيم",    translit: "Al-Halim",     en: "The Forbearing",               sq: "I Përmbajturi" },
  { n: 33, arabic: "ٱلْعَظِيم",    translit: "Al-'Azim",     en: "The Magnificent",              sq: "I Madhërishmi" },
  { n: 34, arabic: "ٱلْغَفُور",    translit: "Al-Ghafur",    en: "The All-Forgiving",            sq: "Falësi" },
  { n: 35, arabic: "ٱلشَّكُور",    translit: "Ash-Shakur",   en: "The Most Appreciative",        sq: "Mirënjohësi" },
  { n: 36, arabic: "ٱلْعَلِيّ",    translit: "Al-'Ali",      en: "The Most High",                sq: "I Larti" },
  { n: 37, arabic: "ٱلْكَبِير",    translit: "Al-Kabir",     en: "The Most Great",               sq: "I Madhi" },
  { n: 38, arabic: "ٱلْحَفِيظ",    translit: "Al-Hafiz",     en: "The Preserver",                sq: "Ruajtësi" },
  { n: 39, arabic: "ٱلْمُقِيت",    translit: "Al-Muqit",     en: "The Sustainer",                sq: "Ushqyesi" },
  { n: 40, arabic: "ٱلْحَسِيب",    translit: "Al-Hasib",     en: "The Reckoner",                 sq: "Llogaritësi" },
  { n: 41, arabic: "ٱلْجَلِيل",    translit: "Al-Jalil",     en: "The Majestic",                 sq: "Madhëriploti" },
  { n: 42, arabic: "ٱلْكَرِيم",    translit: "Al-Karim",     en: "The Most Generous",            sq: "Bujari" },
  { n: 43, arabic: "ٱلرَّقِيب",    translit: "Ar-Raqib",     en: "The Watchful",                 sq: "Vëzhguesi" },
  { n: 44, arabic: "ٱلْمُجِيب",    translit: "Al-Mujib",     en: "The Responsive One",           sq: "Përgjigjësi i lutjeve" },
  { n: 45, arabic: "ٱلْوَاسِع",    translit: "Al-Wasi'",     en: "The All-Encompassing",         sq: "Gjithëpërfshirësi" },
  { n: 46, arabic: "ٱلْحَكِيم",    translit: "Al-Hakim",     en: "The All-Wise",                 sq: "I Urti" },
  { n: 47, arabic: "ٱلْوَدُود",    translit: "Al-Wadud",     en: "The Most Loving",              sq: "I Dashuri" },
  { n: 48, arabic: "ٱلْمَجِيد",    translit: "Al-Majid",     en: "The Glorious",                 sq: "I Lavdishmi" },
  { n: 49, arabic: "ٱلْبَاعِث",    translit: "Al-Ba'ith",    en: "The Resurrector",              sq: "Ringjallësi" },
  { n: 50, arabic: "ٱلشَّهِيد",    translit: "Ash-Shahid",   en: "The All-Witnessing",           sq: "Dëshmitari" },
  { n: 51, arabic: "ٱلْحَقّ",     translit: "Al-Haqq",      en: "The Absolute Truth",           sq: "I Vërteti" },
  { n: 52, arabic: "ٱلْوَكِيل",    translit: "Al-Wakil",     en: "The Trustee",                  sq: "Garantuesi" },
  { n: 53, arabic: "ٱلْقَوِيّ",    translit: "Al-Qawiyy",    en: "The All-Strong",               sq: "I Forti" },
  { n: 54, arabic: "ٱلْمَتِين",    translit: "Al-Matin",     en: "The Firm One",                 sq: "I Patunduri" },
  { n: 55, arabic: "ٱلْوَلِيّ",    translit: "Al-Waliyy",    en: "The Protecting Friend",        sq: "Miku Mbrojtës" },
  { n: 56, arabic: "ٱلْحَمِيد",    translit: "Al-Hamid",     en: "The Praiseworthy",             sq: "I Lavdëruari" },
  { n: 57, arabic: "ٱلْمُحْصِي",   translit: "Al-Muhsi",     en: "The All-Enumerating",          sq: "Llogarimbajtësi" },
  { n: 58, arabic: "ٱلْمُبْدِئ",   translit: "Al-Mubdi'",    en: "The Originator",               sq: "Nismëtari" },
  { n: 59, arabic: "ٱلْمُعِيد",    translit: "Al-Mu'id",     en: "The Restorer",                 sq: "Rikthyesi" },
  { n: 60, arabic: "ٱلْمُحْيِي",   translit: "Al-Muhyi",     en: "The Giver of Life",            sq: "Jetëdhënësi" },
  { n: 61, arabic: "ٱلْمُمِيت",    translit: "Al-Mumit",     en: "The Bringer of Death",         sq: "Jetëmarrësi" },
  { n: 62, arabic: "ٱلْحَيّ",     translit: "Al-Hayy",      en: "The Ever-Living",              sq: "I Gjalli i Përjetshëm" },
  { n: 63, arabic: "ٱلْقَيُّوم",    translit: "Al-Qayyum",    en: "The Self-Sustaining",          sq: "Mbajtësi i Gjithçkaje" },
  { n: 64, arabic: "ٱلْوَاجِد",    translit: "Al-Wajid",     en: "The Perceiver",                sq: "Gjetësi" },
  { n: 65, arabic: "ٱلْمَاجِد",    translit: "Al-Majid",     en: "The Illustrious",              sq: "Fisniku" },
  { n: 66, arabic: "ٱلْوَاحِد",    translit: "Al-Wahid",     en: "The One",                      sq: "I Vetmi" },
  { n: 67, arabic: "ٱلْأَحَد",     translit: "Al-Ahad",      en: "The Unique",                   sq: "Një i Pashoq" },
  { n: 68, arabic: "ٱلصَّمَد",     translit: "As-Samad",     en: "The Eternal Refuge",           sq: "Strehimi i Përjetshëm" },
  { n: 69, arabic: "ٱلْقَادِر",    translit: "Al-Qadir",     en: "The Capable",                  sq: "I Fuqishmi" },
  { n: 70, arabic: "ٱلْمُقْتَدِر",  translit: "Al-Muqtadir",  en: "The All-Powerful",             sq: "I Plotfuqishmi" },
  { n: 71, arabic: "ٱلْمُقَدِّم",   translit: "Al-Muqaddim",  en: "The One Who Brings Forward",   sq: "Përparuesi" },
  { n: 72, arabic: "ٱلْمُؤَخِّر",   translit: "Al-Mu'akhkhir", en: "The One Who Delays",          sq: "Vonuesi" },
  { n: 73, arabic: "ٱلْأَوَّل",    translit: "Al-Awwal",     en: "The First",                    sq: "I Pari" },
  { n: 74, arabic: "ٱلْآخِر",     translit: "Al-Akhir",     en: "The Last",                     sq: "I Fundit" },
  { n: 75, arabic: "ٱلظَّاهِر",    translit: "Az-Zahir",     en: "The Manifest",                 sq: "I Dukshmi" },
  { n: 76, arabic: "ٱلْبَاطِن",    translit: "Al-Batin",     en: "The Hidden",                   sq: "I Padukshmi" },
  { n: 77, arabic: "ٱلْوَالِي",    translit: "Al-Wali",      en: "The Governor",                 sq: "Kujdestari" },
  { n: 78, arabic: "ٱلْمُتَعَالِي",  translit: "Al-Muta'ali",  en: "The Most Exalted",             sq: "I Lartësuari" },
  { n: 79, arabic: "ٱلْبَرّ",     translit: "Al-Barr",      en: "The Source of Goodness",       sq: "Bamirësi" },
  { n: 80, arabic: "ٱلتَّوَّاب",    translit: "At-Tawwab",    en: "The Acceptor of Repentance",   sq: "Pranuesi i Pendimit" },
  { n: 81, arabic: "ٱلْمُنْتَقِم",   translit: "Al-Muntaqim",  en: "The Avenger",                  sq: "Ndëshkuesi" },
  { n: 82, arabic: "ٱلْعَفُوّ",    translit: "Al-'Afuww",    en: "The Pardoner",                 sq: "Shlyesi i Mëkateve" },
  { n: 83, arabic: "ٱلرَّءُوف",    translit: "Ar-Ra'uf",     en: "The Most Kind",                sq: "I Dhembshuri" },
  { n: 84, arabic: "مَالِكُ ٱلْمُلْك", translit: "Malik-ul-Mulk", en: "Master of the Kingdom",     sq: "Sunduesi i Gjithë Pushtetit" },
  { n: 85, arabic: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَام", translit: "Dhul-Jalali wal-Ikram", en: "Lord of Majesty and Honour", sq: "Zotëruesi i Madhështisë dhe Nderit" },
  { n: 86, arabic: "ٱلْمُقْسِط",    translit: "Al-Muqsit",    en: "The Equitable",                sq: "I Paanshmi" },
  { n: 87, arabic: "ٱلْجَامِع",    translit: "Al-Jami'",     en: "The Gatherer",                 sq: "Tubuesi" },
  { n: 88, arabic: "ٱلْغَنِيّ",    translit: "Al-Ghaniyy",   en: "The Self-Sufficient",          sq: "I Vetëmjaftueshmi" },
  { n: 89, arabic: "ٱلْمُغْنِي",    translit: "Al-Mughni",    en: "The Enricher",                 sq: "Pasuruesi" },
  { n: 90, arabic: "ٱلْمَانِع",    translit: "Al-Mani'",     en: "The Preventer",                sq: "Penguesi" },
  { n: 91, arabic: "ٱلضَّارّ",     translit: "Ad-Darr",      en: "The Distresser",               sq: "Dëmtuesi (me urtësi)" },
  { n: 92, arabic: "ٱلنَّافِع",    translit: "An-Nafi'",     en: "The Benefactor",               sq: "Dobiprurësi" },
  { n: 93, arabic: "ٱلنُّور",     translit: "An-Nur",       en: "The Light",                    sq: "Drita" },
  { n: 94, arabic: "ٱلْهَادِي",    translit: "Al-Hadi",      en: "The Guide",                    sq: "Udhëzuesi" },
  { n: 95, arabic: "ٱلْبَدِيع",    translit: "Al-Badi'",     en: "The Incomparable Originator",  sq: "Shpikësi i Pashembullt" },
  { n: 96, arabic: "ٱلْبَاقِي",    translit: "Al-Baqi",      en: "The Everlasting",              sq: "I Përhershmi" },
  { n: 97, arabic: "ٱلْوَارِث",    translit: "Al-Warith",    en: "The Inheritor",                sq: "Trashëgimtari" },
  { n: 98, arabic: "ٱلرَّشِيد",    translit: "Ar-Rashid",    en: "The Guide to the Right Path",  sq: "Udhërrëfyesi i Drejtë" },
  { n: 99, arabic: "ٱلصَّبُور",    translit: "As-Sabur",     en: "The Most Patient",             sq: "I Durueshmi" }
];

// 20-day challenge: days 1-19 have 5 names, day 20 has 4.
export const TOTAL_DAYS = 20;
export function namesForDay(day) {
  return NAMES.slice((day - 1) * 5, day * 5);
}
